const regressionData = {
  Description: "Sales prediction for web shop",
  molar: [
    {
      Description: "WHITE HANGING HEART T-LIGHT HOLDER",
      Quantity: 6,
      REF_YEAR: "08/2012",
      UnitPrice: 2.55,
      CustomerID: 17850,
    },
    {
      Description: "WHITE METAL LANTERN",
      Quantity: 6,
      REF_YEAR: "08/2012",
      UnitPrice: 3.39,
      CustomerID: 17850,
    },
    {
      Description: "CREAM CUPID HEARTS COAT HANGER",
      Quantity: 8,
      REF_YEAR: "08/2012",
      UnitPrice: 2.75,
      CustomerID: 17850,
    },
    {
      Description: "KNITTED UNION FLAG HOT WATER BOTTLE",
      Quantity: 6,
      REF_YEAR: "1/21",
      UnitPrice: 3.39,
      CustomerID: 17850,
    },
    {
      Description: "RED WOOLLY HOTTIE WHITE HEART.",
      Quantity: 6,
      REF_YEAR: "1/21",
      UnitPrice: 3.39,
      CustomerID: 17850,
    },
    {
      Description: "SET 7 BABUSHKA NESTING BOXES",
      Quantity: 2,
      REF_YEAR: "1/21",
      UnitPrice: 7.65,
      CustomerID: 17850,
    },
    {
      Description: "GLASS STAR FROSTED T-LIGHT HOLDER",
      Quantity: 6,
      REF_YEAR: "1/21",
      UnitPrice: 4.25,
      CustomerID: 17850,
    },
    {
      Description: "HAND WARMER UNION JACK",
      Quantity: 6,
      REF_YEAR: "1/21",
      UnitPrice: 1.85,
      CustomerID: 17850,
    },
    {
      Description: "HAND WARMER RED POLKA DOT",
      Quantity: 6,
      REF_YEAR: "1/21",
      UnitPrice: 1.85,
      CustomerID: 17850,
    },
    {
      Description: "ASSORTED COLOUR BIRD ORNAMENT",
      Quantity: 32,
      REF_YEAR: "1/21",
      UnitPrice: 1.69,
      CustomerID: 13047,
    },
    {
      Description: "POPPY'S PLAYHOUSE BEDROOM ",
      Quantity: 6,
      REF_YEAR: "1/21",
      UnitPrice: 2.1,
      CustomerID: 13047,
    },
    {
      Description: "POPPY'S PLAYHOUSE KITCHEN",
      Quantity: 6,
      REF_YEAR: "2/21",
      UnitPrice: 2.1,
      CustomerID: 13047,
    },
    {
      Description: "FELTCRAFT PRINCESS CHARLOTTE DOLL",
      Quantity: 8,
      REF_YEAR: "2/21",
      UnitPrice: 3.75,
      CustomerID: 13047,
    },
    {
      Description: "IVORY KNITTED MUG COSY ",
      Quantity: 6,
      REF_YEAR: "2/21",
      UnitPrice: 1.65,
      CustomerID: 13047,
    },
    {
      Description: "BOX OF 6 ASSORTED COLOUR TEASPOONS",
      Quantity: 6,
      REF_YEAR: "2/21",
      UnitPrice: 4.25,
      CustomerID: 13047,
    },
    {
      Description: "BOX OF VINTAGE JIGSAW BLOCKS ",
      Quantity: 3,
      REF_YEAR: "2/21",
      UnitPrice: 4.95,
      CustomerID: 13047,
    },
    {
      Description: "BOX OF VINTAGE ALPHABET BLOCKS",
      Quantity: 2,
      REF_YEAR: "2/21",
      UnitPrice: 9.95,
      CustomerID: 13047,
    },
    {
      Description: "HOME BUILDING BLOCK WORD",
      Quantity: 3,
      REF_YEAR: "2/21",
      UnitPrice: 5.95,
      CustomerID: 13047,
    },
    {
      Description: "LOVE BUILDING BLOCK WORD",
      Quantity: 3,
      REF_YEAR: "2/21",
      UnitPrice: 5.95,
      CustomerID: 13047,
    },
    {
      Description: "RECIPE BOX WITH METAL HEART",
      Quantity: 4,
      REF_YEAR: "2/21",
      UnitPrice: 7.95,
      CustomerID: 13047,
    },
    {
      Description: "DOORMAT NEW ENGLAND",
      Quantity: 4,
      REF_YEAR: "2/21",
      UnitPrice: 7.95,
      CustomerID: 13047,
    },
    {
      Description: "JAM MAKING SET WITH JARS",
      Quantity: 6,
      REF_YEAR: "3/21",
      UnitPrice: 4.25,
      CustomerID: 13047,
    },
    {
      Description: "RED COAT RACK PARIS FASHION",
      Quantity: 3,
      REF_YEAR: "3/21",
      UnitPrice: 4.95,
      CustomerID: 13047,
    },
    {
      Description: "YELLOW COAT RACK PARIS FASHION",
      Quantity: 3,
      REF_YEAR: "3/21",
      UnitPrice: 4.95,
      CustomerID: 13047,
    },
    {
      Description: "BLUE COAT RACK PARIS FASHION",
      Quantity: 3,
      REF_YEAR: "3/21",
      UnitPrice: 4.95,
      CustomerID: 13047,
    },
    {
      Description: "BATH BUILDING BLOCK WORD",
      Quantity: 3,
      REF_YEAR: "3/21",
      UnitPrice: 5.95,
      CustomerID: 13047,
    },
    {
      Description: "ALARM CLOCK BAKELIKE PINK",
      Quantity: 24,
      REF_YEAR: "3/21",
      UnitPrice: 3.75,
      CustomerID: 12583,
    },
    {
      Description: "ALARM CLOCK BAKELIKE RED ",
      Quantity: 24,
      REF_YEAR: "3/21",
      UnitPrice: 3.75,
      CustomerID: 12583,
    },
    {
      Description: "ALARM CLOCK BAKELIKE GREEN",
      Quantity: 12,
      REF_YEAR: "3/21",
      UnitPrice: 3.75,
      CustomerID: 12583,
    },
    {
      Description: "PANDA AND BUNNIES STICKER SHEET",
      Quantity: 12,
      REF_YEAR: "3/21",
      UnitPrice: 0.85,
      CustomerID: 12583,
    },
    {
      Description: "STARS GIFT TAPE ",
      Quantity: 24,
      REF_YEAR: "4/21",
      UnitPrice: 0.65,
      CustomerID: 12583,
    },
    {
      Description: "INFLATABLE POLITICAL GLOBE ",
      Quantity: 48,
      REF_YEAR: "4/21",
      UnitPrice: 0.85,
      CustomerID: 12583,
    },
    {
      Description: "VINTAGE HEADS AND TAILS CARD GAME ",
      Quantity: 24,
      REF_YEAR: "4/21",
      UnitPrice: 1.25,
      CustomerID: 12583,
    },
    {
      Description: "SET/2 RED RETROSPOT TEA TOWELS ",
      Quantity: 18,
      REF_YEAR: "4/21",
      UnitPrice: 2.95,
      CustomerID: 12583,
    },
    {
      Description: "ROUND SNACK BOXES SET OF4 WOODLAND ",
      Quantity: 24,
      REF_YEAR: "4/21",
      UnitPrice: 2.95,
      CustomerID: 12583,
    },
    {
      Description: "SPACEBOY LUNCH BOX ",
      Quantity: 24,
      REF_YEAR: "4/21",
      UnitPrice: 1.95,
      CustomerID: 12583,
    },
    {
      Description: "LUNCH BOX I LOVE LONDON",
      Quantity: 24,
      REF_YEAR: "4/21",
      UnitPrice: 1.95,
      CustomerID: 12583,
    },
    {
      Description: "CIRCUS PARADE LUNCH BOX ",
      Quantity: 24,
      REF_YEAR: "4/21",
      UnitPrice: 1.95,
      CustomerID: 12583,
    },
    {
      Description: "CHARLOTTE BAG DOLLY GIRL DESIGN",
      Quantity: 20,
      REF_YEAR: "4/21",
      UnitPrice: 0.85,
      CustomerID: 12583,
    },
    {
      Description: "RED TOADSTOOL LED NIGHT LIGHT",
      Quantity: 24,
      REF_YEAR: "4/21",
      UnitPrice: 1.65,
      CustomerID: 12583,
    },
    {
      Description: " SET 2 TEA TOWELS I LOVE LONDON ",
      Quantity: 24,
      REF_YEAR: "4/21",
      UnitPrice: 2.95,
      CustomerID: 12583,
    },
    {
      Description: "VINTAGE SEASIDE JIGSAW PUZZLES",
      Quantity: 12,
      REF_YEAR: "4/21",
      UnitPrice: 3.75,
      CustomerID: 12583,
    },
    {
      Description: "MINI JIGSAW CIRCUS PARADE ",
      Quantity: 24,
      REF_YEAR: "4/21",
      UnitPrice: 0.42,
      CustomerID: 12583,
    },
    {
      Description: "MINI JIGSAW SPACEBOY",
      Quantity: 24,
      REF_YEAR: "4/21",
      UnitPrice: 0.42,
      CustomerID: 12583,
    },
    {
      Description: "MINI PAINT SET VINTAGE ",
      Quantity: 36,
      REF_YEAR: "4/21",
      UnitPrice: 0.65,
      CustomerID: 12583,
    },
    {
      Description: "POSTAGE",
      Quantity: 3,
      REF_YEAR: "4/21",
      UnitPrice: 18,
      CustomerID: 12583,
    },
    {
      Description: "PAPER CHAIN KIT 50'S CHRISTMAS ",
      Quantity: 80,
      REF_YEAR: "5/21",
      UnitPrice: 2.55,
      CustomerID: 13748,
    },
    {
      Description: "HAND WARMER RED POLKA DOT",
      Quantity: 6,
      REF_YEAR: "5/21",
      UnitPrice: 1.85,
      CustomerID: 17850,
    },
    {
      Description: "HAND WARMER UNION JACK",
      Quantity: 6,
      REF_YEAR: "5/21",
      UnitPrice: 1.85,
      CustomerID: 17850,
    },
    {
      Description: "WHITE HANGING HEART T-LIGHT HOLDER",
      Quantity: 6,
      REF_YEAR: "5/21",
      UnitPrice: 2.55,
      CustomerID: 17850,
    },
    {
      Description: "WHITE METAL LANTERN",
      Quantity: 6,
      REF_YEAR: "5/21",
      UnitPrice: 3.39,
      CustomerID: 17850,
    },
    {
      Description: "CREAM CUPID HEARTS COAT HANGER",
      Quantity: 8,
      REF_YEAR: "5/21",
      UnitPrice: 2.75,
      CustomerID: 17850,
    },
    {
      Description: "EDWARDIAN PARASOL RED",
      Quantity: 6,
      REF_YEAR: "06/21",
      UnitPrice: 4.95,
      CustomerID: 17850,
    },
    {
      Description: "RETRO COFFEE MUGS ASSORTED",
      Quantity: 6,
      REF_YEAR: "06/21",
      UnitPrice: 1.06,
      CustomerID: 17850,
    },
    {
      Description: "SAVE THE PLANET MUG",
      Quantity: 6,
      REF_YEAR: "06/21",
      UnitPrice: 1.06,
      CustomerID: 17850,
    },
    {
      Description: "VINTAGE BILLBOARD DRINK ME MUG",
      Quantity: 6,
      REF_YEAR: "06/21",
      UnitPrice: 1.06,
      CustomerID: 17850,
    },
    {
      Description: "VINTAGE BILLBOARD LOVE/HATE MUG",
      Quantity: 6,
      REF_YEAR: "06/21",
      UnitPrice: 1.06,
      CustomerID: 17850,
    },
    {
      Description: "WOOD 2 DRAWER CABINET WHITE FINISH",
      Quantity: 2,
      REF_YEAR: "06/21",
      UnitPrice: 4.95,
      CustomerID: 17850,
    },
    {
      Description: "WOOD S/3 CABINET ANT WHITE FINISH",
      Quantity: 4,
      REF_YEAR: "06/21",
      UnitPrice: 6.95,
      CustomerID: 17850,
    },
    {
      Description: "WOODEN PICTURE FRAME WHITE FINISH",
      Quantity: 6,
      REF_YEAR: "06/21",
      UnitPrice: 2.1,
      CustomerID: 17850,
    },
    {
      Description: "WOODEN FRAME ANTIQUE WHITE ",
      Quantity: 6,
      REF_YEAR: "06/21",
      UnitPrice: 2.55,
      CustomerID: 17850,
    },
    {
      Description: "KNITTED UNION FLAG HOT WATER BOTTLE",
      Quantity: 6,
      REF_YEAR: "07/21",
      UnitPrice: 3.39,
      CustomerID: 17850,
    },
    {
      Description: "RED WOOLLY HOTTIE WHITE HEART.",
      Quantity: 6,
      REF_YEAR: "07/21",
      UnitPrice: 3.39,
      CustomerID: 17850,
    },
    {
      Description: "SET 7 BABUSHKA NESTING BOXES",
      Quantity: 2,
      REF_YEAR: "07/21",
      UnitPrice: 7.65,
      CustomerID: 17850,
    },
    {
      Description: "GLASS STAR FROSTED T-LIGHT HOLDER",
      Quantity: 6,
      REF_YEAR: "07/21",
      UnitPrice: 4.25,
      CustomerID: 17850,
    },
    {
      Description: "VICTORIAN SEWING BOX LARGE",
      Quantity: 32,
      REF_YEAR: "07/21",
      UnitPrice: 10.95,
      CustomerID: 15100,
    },
    {
      Description: "WHITE HANGING HEART T-LIGHT HOLDER",
      Quantity: 6,
      REF_YEAR: "07/21",
      UnitPrice: 2.55,
      CustomerID: 17850,
    },
    {
      Description: "WHITE METAL LANTERN",
      Quantity: 6,
      REF_YEAR: "08/21",
      UnitPrice: 3.39,
      CustomerID: 17850,
    },
    {
      Description: "CREAM CUPID HEARTS COAT HANGER",
      Quantity: 8,
      REF_YEAR: "08/21",
      UnitPrice: 2.75,
      CustomerID: 17850,
    },
    {
      Description: "EDWARDIAN PARASOL RED",
      Quantity: 6,
      REF_YEAR: "08/21",
      UnitPrice: 4.95,
      CustomerID: 17850,
    },
    {
      Description: "RETRO COFFEE MUGS ASSORTED",
      Quantity: 6,
      REF_YEAR: "08/21",
      UnitPrice: 1.06,
      CustomerID: 17850,
    },
    {
      Description: "SAVE THE PLANET MUG",
      Quantity: 6,
      REF_YEAR: "08/21",
      UnitPrice: 1.06,
      CustomerID: 17850,
    },
    {
      Description: "VINTAGE BILLBOARD DRINK ME MUG",
      Quantity: 6,
      REF_YEAR: "08/21",
      UnitPrice: 1.06,
      CustomerID: 17850,
    },
    {
      Description: "VINTAGE BILLBOARD LOVE/HATE MUG",
      Quantity: 6,
      REF_YEAR: "08/21",
      UnitPrice: 1.06,
      CustomerID: 17850,
    },
    {
      Description: "WOOD 2 DRAWER CABINET WHITE FINISH",
      Quantity: 2,
      REF_YEAR: "09/21",
      UnitPrice: 4.95,
      CustomerID: 17850,
    },
    {
      Description: "WOOD S/3 CABINET ANT WHITE FINISH",
      Quantity: 4,
      REF_YEAR: "09/21",
      UnitPrice: 6.95,
      CustomerID: 17850,
    },
    {
      Description: "WOODEN PICTURE FRAME WHITE FINISH",
      Quantity: 6,
      REF_YEAR: "09/21",
      UnitPrice: 2.1,
      CustomerID: 17850,
    },
    {
      Description: "WOODEN FRAME ANTIQUE WHITE ",
      Quantity: 6,
      REF_YEAR: "09/21",
      UnitPrice: 2.55,
      CustomerID: 17850,
    },
    {
      Description: "KNITTED UNION FLAG HOT WATER BOTTLE",
      Quantity: 6,
      REF_YEAR: "09/21",
      UnitPrice: 3.39,
      CustomerID: 17850,
    },
    {
      Description: "RED WOOLLY HOTTIE WHITE HEART.",
      Quantity: 6,
      REF_YEAR: "10/21",
      UnitPrice: 3.39,
      CustomerID: 17850,
    },
    {
      Description: "SET 7 BABUSHKA NESTING BOXES",
      Quantity: 2,
      REF_YEAR: "10/21",
      UnitPrice: 7.65,
      CustomerID: 17850,
    },
    {
      Description: "GLASS STAR FROSTED T-LIGHT HOLDER",
      Quantity: 6,
      REF_YEAR: "10/21",
      UnitPrice: 4.25,
      CustomerID: 17850,
    },
    {
      Description: "HOT WATER BOTTLE TEA AND SYMPATHY",
      Quantity: 48,
      REF_YEAR: "11/21",
      UnitPrice: 3.45,
      CustomerID: 15291,
    },
    {
      Description: "WHITE METAL LANTERN",
      Quantity: 6,
      REF_YEAR: "11/21",
      UnitPrice: 3.39,
      CustomerID: 17850,
    },
    {
      Description: "CREAM CUPID HEARTS COAT HANGER",
      Quantity: 8,
      REF_YEAR: "11/21",
      UnitPrice: 2.75,
      CustomerID: 17850,
    },
    {
      Description: "EDWARDIAN PARASOL BLACK",
      Quantity: 6,
      REF_YEAR: "12/21",
      UnitPrice: 4.95,
      CustomerID: 17850,
    },
    {
      Description: "EDWARDIAN PARASOL RED",
      Quantity: 6,
      REF_YEAR: "12/21",
      UnitPrice: 4.95,
      CustomerID: 17850,
    },
    {
      Description: "RETRO COFFEE MUGS ASSORTED",
      Quantity: 6,
      REF_YEAR: "12/21",
      UnitPrice: 1.06,
      CustomerID: 17850,
    },
    {
      Description: "SAVE THE PLANET MUG",
      Quantity: 6,
      REF_YEAR: "12/21",
      UnitPrice: 1.06,
      CustomerID: 17850,
    },
    {
      Description: "VINTAGE BILLBOARD DRINK ME MUG",
      Quantity: 6,
      REF_YEAR: "12/21",
      UnitPrice: 1.06,
      CustomerID: 17850,
    },
  ],
  data: [
    // {
    //   NUTS1: "AT3",
    //   NUTS2: "AT32",
    //   AGE_AT_MARRIAGE: "15 to 19 years old",
    //   REF_YEAR: "2012",
    //   values: [{ WIVES: 432, HUSBANDS: 55 }],
    // },
    // {
    //   NUTS1: "AT3",
    //   NUTS2: "AT32",
    //   AGE_AT_MARRIAGE: "15 to 19 years old",
    //   REF_YEAR: "2012",
    //   values: [{ WIVES: 432, HUSBANDS: 76 }],
    // },
    // {
    //   NUTS1: "AT3",
    //   NUTS2: "AT32",
    //   AGE_AT_MARRIAGE: "15 to 19 years old",
    //   REF_YEAR: "2012",
    //   values: [{ WIVES: 22487, HUSBANDS: 85 }],
    // },
    // {
    //   NUTS1: "AT3",
    //   NUTS2: "AT32",
    //   AGE_AT_MARRIAGE: "15 to 19 years old",
    //   REF_YEAR: "2013",
    //   values: [{ WIVES: 23412, HUSBANDS: 65 }],
    // },
    // {
    //   NUTS1: "AT3",
    //   NUTS2: "AT32",
    //   AGE_AT_MARRIAGE: "15 to 19 years old",
    //   REF_YEAR: "2013",
    //   values: [{ WIVES: 23834, HUSBANDS: 65 }],
    // },
    // {
    //   NUTS1: "AT3",
    //   NUTS2: "AT32",
    //   AGE_AT_MARRIAGE: "15 to 19 years old",
    //   REF_YEAR: "2012",
    //   values: [{ WIVES: 330, HUSBANDS: 67 }],
    // },
    // {
    //   NUTS1: "AT3",
    //   NUTS2: "AT32",
    //   AGE_AT_MARRIAGE: "15 to 19 years old",
    //   REF_YEAR: "2011",
    //   values: [{ WIVES: 140, HUSBANDS: 65 }],
    // },
    // {
    //   NUTS1: "AT3",
    //   NUTS2: "AT32",
    //   AGE_AT_MARRIAGE: "15 to 19 years old",
    //   REF_YEAR: "2011",
    //   values: [{ WIVES: 244, HUSBANDS: 43 }],
    // },
    // {
    //   NUTS1: "AT3",
    //   NUTS2: "AT32",
    //   AGE_AT_MARRIAGE: "15 to 19 years old",
    //   REF_YEAR: "2011",
    //   values: [{ WIVES: 2263, HUSBANDS: 53 }],
    // },
    // {
    //   NUTS1: "AT3",
    //   NUTS2: "AT32",
    //   AGE_AT_MARRIAGE: "15 to 19 years old",
    //   REF_YEAR: "2012",
    //   values: [{ WIVES: 2242, HUSBANDS: 41 }],
    // },
    // {
    //   NUTS1: "AT3",
    //   NUTS2: "AT32",
    //   AGE_AT_MARRIAGE: "15 to 19 years old",
    //   REF_YEAR: "2012",
    //   values: [{ WIVES: 2310, HUSBANDS: 46 }],
    // },
    {
      NUTS1: "AT3",
      NUTS2: "AT32",
      AGE_AT_MARRIAGE: "15 to 19 years old",
      REF_YEAR: "2012",
      values: [{ WIVES: 300, HUSBANDS: 22 }],
    },
    {
      NUTS1: "AT3",
      NUTS2: "AT32",
      AGE_AT_MARRIAGE: "15 to 19 years old",
      REF_YEAR: "2012",
      values: [{ WIVES: 450, HUSBANDS: 35 }],
    },
    {
      NUTS1: "AT3",
      NUTS2: "AT32",
      AGE_AT_MARRIAGE: "15 to 19 years old",
      REF_YEAR: "2013",
      values: [{ WIVES: 560, HUSBANDS: 19 }],
    },
    {
      NUTS1: "AT3",
      NUTS2: "AT32",
      AGE_AT_MARRIAGE: "15 to 19 years old",
      REF_YEAR: "2014",
      values: [{ WIVES: 450, HUSBANDS: 54 }],
    },
    {
      NUTS1: "AT3",
      NUTS2: "AT32",
      AGE_AT_MARRIAGE: "15 to 19 years old",
      REF_YEAR: "2015",
      values: [{ WIVES: 550, HUSBANDS: 122 }],
    },
    {
      NUTS1: "AT3",
      NUTS2: "AT32",
      AGE_AT_MARRIAGE: "15 to 19 years old",
      REF_YEAR: "2016",
      values: [{ WIVES: 653, HUSBANDS: 19 }],
    },
    {
      NUTS1: "AT3",
      NUTS2: "AT32",
      AGE_AT_MARRIAGE: "15 to 19 years old",
      REF_YEAR: "2017",
      values: [{ WIVES: 645, HUSBANDS: 17 }],
    },
    {
      NUTS1: "AT3",
      NUTS2: "AT32",
      AGE_AT_MARRIAGE: "15 to 19 years old",
      REF_YEAR: "2018",
      values: [{ WIVES: 661, HUSBANDS: 35 }],
    },
    {
      NUTS1: "AT3",
      NUTS2: "AT32",
      AGE_AT_MARRIAGE: "15 to 19 years old",
      REF_YEAR: "2019",
      values: [{ WIVES: 629, HUSBANDS: 27 }],
    },
    {
      NUTS1: "AT3",
      NUTS2: "AT32",
      AGE_AT_MARRIAGE: "15 to 19 years old",
      REF_YEAR: "2020",
      values: [{ WIVES: 800, HUSBANDS: 27 }],
    },
    {
      NUTS1: "AT3",
      NUTS2: "AT32",
      AGE_AT_MARRIAGE: "15 to 19 years old",
      REF_YEAR: "2021",
      values: [{ WIVES: 850, HUSBANDS: 27 }],
    },
  ],
};

export default regressionData;
